[package]
name = "balde"
version = "0.1.0"
authors = ["Jayson Reis <santosdosreis@gmail.com>"]
edition = "2018"

[dependencies]
foreign-types = "^0.3.2"
glib = "^0.6.1"
glib-sys = "^0.7.0"
bitflags = "*"
lazy_static = "*"

[dependencies.balde-sys]
path = "../balde-sys"